### ISSUE TITLE
Tracking issue: Improvements in Docker Agent

### ISSUE THREAD

**Issue by nrybowski** [UCL-INGI/INGInious#950]
This issue tracks the improvements that are expected from a future refactor of the Docker Agent base code.

# Must Have
- [ ] `create_container()` and `create_container_student()` are quite similar. A common routine must be implemented.
- [ ] Arguments of  `create_container()` and `create_container_student()` are quite numerous and extending them is quite error prone. They should be absracted in DataClasses.
- [ ] The communication system between the child containers and the parent grading container should leverage the Docker network stack .
- [ ] Improve error handling from the Docker API calls (see  `create_container()` and `create_container_student()`).

# Nice to have
